### ISSUE TITLE
wicked pdf with custom fonts

### ISSUE THREAD

**Issue by maaris** [mileszs/wicked_pdf#334]
Hello!
I am using wicked_pdf gem for the pdf generation! There is some problems using custom fonts. I have tried using it like this:

``` css
@font-face {
    font-family:'ITC Franklin Gothic STD';
    font-weight:300;
    font-style:normal;
    src:font-url('itcfranklingothicstd-book.eot');
    src:font-url('itcfranklingothicstd-book.eot?#iefix') format('embedded-opentype'),
        font-url('itcfranklingothicstd-book.woff') format('woff'),
        font-url('itcfranklingothicstd-book.ttf') format('truetype'),
        font-url('itcfranklingothicstd-book.svg#iefix') format('svg');
    }
```

I even tried to convert convert font to base64 but without success.

``` css
@font-face {
    font-family: 'ITC Franklin Gothic STD';
    font-style: normal;
    font-weight: 300;
    src: url(data:font/opentype;charset=utf-8;base64,d09GRgABAAAAAD00AA4A---[large string ommited]----3MAuAH/hbAEjQA=) format("woff"),
    url(data:font/truetype;charset=utf-8;base64,AAEAAAARAQAABAAQRFNJRwAAAAEAAJUIAAA---[large string ommited]-----wAAAAAAAAAAAAEAAAAA) format("truetype");
}
```

Should it work by default or am i missing something?

**Comment by ldrbrandon** [comment]
@unixmonkey I'm trying to use/embed Open Sans light, regular and bold in a pdf. Currently I use the same method you suggested in this post with an absolute url. I have also tried the base64 encoding the reference and that seemed to work as well. The issue however, is that I specify them with different names,
ie: @font-face {  font-family: 'Open Sans Light'; ...  }
@font-face {  font-family: 'Open Sans Regular'; ...  }
@font-face {  font-family: 'Open Sans Bold'; ...  }
But in production it only ever uses regular and bold. and in my css file, when I want a specific element to be a certain one, I use "font-famil: 'Open Sans Light' !important;" and those elements still just get rendered as regular. Even when I specify bold on certain elements, it makes it regular.

Any solutions to this? I feel like I can't be the first one to experience this.

**Comment by unixmonkey** [comment]
I'm not 100% sure, but this looks like it might help:
http://stackoverflow.com/a/25533201/23915

It seems to me from reading a handful of pages that browsers don't all ship with Open Sans Light variant, so you'll need to download or include it yourself, or use Google Fonts, then use CSS to specify the font-weight yourself:

```css
body {
  font-family: 'Open Sans';
  font-style: Light;
}
```

Let me know how it goes!

**Comment by ldrbrandon** [comment]
Unfortunately that didn't work either. I'm actually using the base64 encoding method you've shown in another post @unixmonkey to base64 encode my fonts. I have them in the app/assets/fonts folder in my Rails app. If that helps to better diagnose the issue.

And actually, locally, I can specify them like so: "Open Sans Light", "Open Sans", "Open Sans Bold" and everything works how I want it. However, it does not use light in our production environment.

    @font-face {
        font-family: 'Open Sans Light';
        font-weight: 300;
        src: url(asset_data_base64('OpenSans-Light-webfont.ttf')),
        url(asset_data_base64('OpenSans-Light-webfont.woff'));
    }
    @font-face {
        font-family: 'Open Sans';
        font-style: normal;
        font-weight: 400;
        src: url(asset_data_base64('OpenSans-Regular-webfont.ttf')),
        url(asset_data_base64('OpenSans-Regular-webfont.woff'));
    }
    @font-face {
        font-family: 'Open Sans Bold';
        font-style: normal;
        font-weight: 600;
        src: url(asset_data_base64('OpenSans-Bold-webfont.ttf')),
        url(asset_data_base64('OpenSans-Bold-webfont.woff'));
    }

**Comment by GoodJob** [comment]
I have uploaded the font to my server /usr/share/fonts/truetype/freefont, and it works from now on :)

**Comment by ldrbrandon** [comment]
@GoodJob Yea I actually figured out that installing the fonts on the server fixes this issue too! Thanks for confirming.

**Comment by aldrienht** [comment]
Hi there! I'm having trouble with font style/size when I deployed by Rails app in Amazon EC2 Linux.

The rendering of font style and sizes are bit different in my local development.

Even I already set the font, as @unixmonkey  suggested.
That's why I got some misalignment issues.

Please help!

**Comment by alexshenia** [comment]
@aldrienht  @unixmonkey i have same issue with fonts on AWS, i have tried different ways to fix it
1) use font-face from google fonts
2) use font-face from assets

**Comment by aldrienht** [comment]
Hi @alexshenia , i fixed it. I created a gist, please check here [Matching System Font with your local environment and Amazon Linux](https://gist.github.com/aldrienht/cdedca54a9398bdc6f7a3e12d7a222db)

That is manual way. I dont know if there is other way to do it. 
But for now, that fixed my problem.

**Comment by katebeavis** [comment]
I tried everything, spent a day trying to figure it out, encoding in base64 etc. Turns out simply converting from ttf to otf got it to work for me! Hope this helps somebody....

**Comment by abo-elleef** [comment]
@unixmonkey thank you 
you saved my day

**Comment by valterbarros** [comment]
@unixmonkey I used your solution but my fonts are with low quality
![The Finished Dish](https://trello-attachments.s3.amazonaws.com/59a0d63c8bd1390836d9e238/5a1de6b4efb02f6048ed5cef/0375ec892e89043458d018bd5dd5509b/Screenshot_from_2017-11-30_11-51-13.png)

**Comment by alikazmilwl** [comment]
@unixmonkey I am trying to load a custom font: dameron

In my html, which is converted to pdf, there is style tag.

<style>
@font-face {
font-weight: 400;	font-family: "demarow";
	src: local('☺'), url('/system/fonts/files/000/000/011/original/dameron.otf?1522910532') format('opentype');
}
</style>

in my span:

<span style='font-family: demarow !important'>
    			
    			NAME
    		</span>

But the font is not loaded in pdf. It is loading in html format. What can be the problem? Thanks

**Comment by unixmonkey** [comment]
@alikazmilwl See this comment for a working example: https://github.com/mileszs/wicked_pdf/issues/334#issuecomment-56982265

I'm not sure if the `src: local('☺')` might be confusing something, so until you get it working, I'd remove it to make sure, and add it back once you get a working solution.

I'd also suggest removing the `?1522910532` from the url. Once the temporary file that gets converted to a PDF is on disk, I think that would be a bad filename. And crazy as it is, I'd suggest quoting the `font-family: 'demarow'` with single quotes. I've seen it make a difference.

Let me know how it goes!

**Comment by soundasleep** [comment]
I was having a weird issue where installing the custom font locally (on Windows) was causing the rendered PDF to render font as blank text. The issue wasn't occurring before I had installed the font locally on Windows.

However by changing the HTML PDF to use a `<link>` tag, rather than `@import`ing it in the CSS, this resolved the font rendering issue. In other words, I removed

```css
@import url("https://fonts.googleapis.com/css?family=Hind:300,500,700");
```

and replaced it with

```html
<link href="https://fonts.googleapis.com/css?family=Hind:300,500,700" rel="stylesheet" type="text/css">
```

and everything works again.

**Comment by daveomcd** [comment]
I was having issues with the custom fonts showing in my development environment after cloning an existing repository.  Running this commend resolved the issue for me...

`RAILS_ENV=development bundle exec rake assets:precompile`

**Comment by AlexVentura** [comment]
Hey guys I'm having kind of the same issue. I'm using [bootstrap 4](https://github.com/twbs/bootstrap-rubygem) but I'm getting different font in the PDF report in production droplet from DigitalOcean.
I also deployed the same app to Heroku and it is showing the same bootstrap 4 font as in development.
Not sure what should be causing this difference, any thoughts?

> Production droplet DigitalOcean:
<img width="839" alt="prod_do" src="https://user-images.githubusercontent.com/13169164/53131572-c7e7b980-3532-11e9-96c8-53b6e7392f00.png">

> Production dyne Heroku
<img width="830" alt="prod_heroku" src="https://user-images.githubusercontent.com/13169164/53131554-b6061680-3532-11e9-801c-16edfc5e54e0.png">

> Local development machine
<img width="846" alt="dev_local" src="https://user-images.githubusercontent.com/13169164/53131590-d03ff480-3532-11e9-9d72-c47f4ec2c2cc.png">

Clearly the number `1` in the first image which is production server in DO renders a different font than production in Heroku and in local machine. This is my layout:
```html
<!DOCTYPE html>
<html lang='es'>
<head>
  <meta charset='utf-8'>
  <title>MyBusinessApp</title>
  <%= wicked_pdf_stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" -%>
</head>
<body>
  <%= yield %>
</body>
</html>
```
Any idea what's going on?

**Comment by unixmonkey** [comment]
@AlexVentura When you view an HTML webpage locally, the browser uses your local fonts installed as part of your OS or browser. When you are generating a PDF, that's still happening, but it's happening on the server, which may have different fonts installed, or may be missing some fonts, and falling back to something different.

Even the same font can be different on some systems. [This StackOverflow answer](https://stackoverflow.com/a/37013543/23915) says it way better than I could.

You probably either need to install and configure some font packages on one (or all) of your systems, or override the Bootstrap styles with a custom font, and providing that font file in your CSS like what's shown above.

If your site is multilingual, make sure you have the font support for other languages installed too, or you could get squares or question marks for some characters or glyphs.

**Comment by AlexVentura** [comment]
@unixmonkey thanks for your quickly response and also for elaborating this for me. So [this is the way I should go](https://github.com/mileszs/wicked_pdf/issues/334#issuecomment-56982265) ?

**Comment by unixmonkey** [comment]
@AlexVentura In general, I think so. In general I find it's often easier to control for the code you can deploy than the system it runs on, especially if you are running on different platforms.

**Comment by AlexVentura** [comment]
@unixmonkey Great! I'm going to try that out and if it fixes this situation, I'll come back to confirm your solution for reference for anyone else. Thx in advance dude!

**Comment by mirelaf** [comment]
@AlexVentura how dit it go, have you found a solution? Having the same issue now. Thanks!

**Comment by AlexVentura** [comment]
@mirelaf I followed [this](http://chapter31.com/2012/09/24/installing-new-fonts-on-ubuntu-server/) to install Helvetica font, I did everything but I haven't found a way to render reports using that font.

**Comment by jvitormichels** [comment]
I did it like this and it worked
In my haml file there is this block to import the font file and give it an alias (in this case, Helvetica)
```
:sass
  @font-face
      font-family: 'Helvetica'
      font-style: 300
      src: url('/www/myShop/app/assets/fonts/Helvetica.ttf') format('truetype')
```
/www/myShop is the Rails.root of my project, and so the rest of the url is the absolute path for my font file
And then I simply used it in my elements
```
.page-inner
    font-family: Helvetica
```
If it was a html, it would be used the same way, but with curly brackets and etc

**Comment by johnharlan** [comment]
@unixmonkey Curious if you have used this recently. I am going the route of base64 the font instead of referencing a file. It is working elsewhere in my app and other styles within my stylesheet are working in my PDF template, but the font will not work. Feels like I have tried everything. 

Ruby 3.2.0
Rails 6.1.4

fonts.scss
`@font-face {
font-family: "GeoSlab";
font-weight: 400;
font-style: normal;
src: url(data:font/truetype;base64,AAEAAAAQA---- long string ---) format(truetype)`

pdf_template.html.erb
`
<%= stylesheet_link_tag wicked_pdf_asset_base64  "global" %>
<%= stylesheet_link_tag wicked_pdf_asset_base64  "fonts" %>

<style>
  .geoslab-font {
    font-family: 'GeoSlab';
    font-style: normal; 
  }
</style>`

**Comment by unixmonkey** [comment]
@johnharlan Does it work with a different font? Or if converted to OpenType? I don't remember if I've tried base64-ing fonts before.

**Comment by limjinsun** [comment]
can't render custom font at all. Is there any guide to this? Would you be able to update custom font guide on your readme.md?

**Comment by unixmonkey** [comment]
> can't render custom font at all.

@limjinsun What have you tried?

If you are using a relative-path in your css like `html { font-family: '/fonts/foo.ttf'; }`, that won't work, it needs to be a full path like `html { font-family: 'https://example.com/fonts/foo.ttf'; }`, or `html { font-family: 'file:///path/to/my/rails/app/assets/fonts/foo.ttf'; }`

One thing to keep in mind is that your html in the view is first saved to a local HTML file, so if the server that has the font uses CORS, you can't load it.

If you download the font file and reference it from the file-system locally, you'll need the WickedPdf `config.enable_local_file_access = true` config option set, or you'll need to embed the font as `base64`.

If you are using newer browser features, don't. I'm not sure off the top of my head if `@font-face` or `@import` stuff works. Stick with CSS and `font-family`. Sometimes single quotes work around the font names, when double quotes don't...no idea why.

Remember that your server may not have normal fonts installed, especially international ones. Look up your distribution's way to add more system font packages if you depend on a system font.

Whatever it is, I'm pretty sure it's fixable, but I don't know enough about your setup.

There's no official guide, but if you come up with a good one, I'd be happy to add it to the README.
